In [74]:
import numpy as np

a= np.array([5,6,9])

In [2]:
a[0]

5

In [3]:
a[1]

6

In [75]:
a.ndim

1

In [17]:
a = np.array([[1,2],[3,4],[5,6]]) 

In [18]:
a.ndim

2

In [13]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [14]:
arr.ndim

2

In [20]:
arr.itemsize

8

In [21]:
a.dtype

dtype('int64')

In [22]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], dtype = np.float)

In [24]:
arr.itemsize

8

In [25]:
arr

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [26]:
arr.size

12

In [27]:
arr.shape

(3, 4)

In [28]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],dtype = complex)

In [29]:
arr

array([[ 1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j],
       [ 5.+0.j,  6.+0.j,  7.+0.j,  8.+0.j],
       [ 9.+0.j, 10.+0.j, 11.+0.j, 12.+0.j]])

In [30]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
np.arange(1,5)

array([1, 2, 3, 4])

In [33]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [34]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [35]:
np.linspace(1,20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [36]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [37]:
np.linspace(1,20,20)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [38]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [39]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
arr.shape

(3, 4)

In [41]:
arr.reshape(2,3)

ValueError: cannot reshape array of size 12 into shape (2,3)

In [42]:
arr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [43]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [44]:
arr.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [45]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
arr.min()

1

In [47]:
arr.max()

12

In [48]:
arr.sum()

78

In [49]:
a.sum(axis = 0)

array([ 9, 12])

In [50]:
arr.sum(axis = 0)

array([15, 18, 21, 24])

In [51]:
arr.sum(axis = 1)

array([10, 26, 42])

In [52]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [53]:
np.std(a)

1.707825127659933

In [54]:
np.std(arr)

3.452052529534663

In [63]:
a = np.array([[1,2] , [3,4]])

In [64]:
b = np.array([[5,6] , [7,8]])

In [65]:
a

array([[1, 2],
       [3, 4]])

In [66]:
b

array([[5, 6],
       [7, 8]])

In [67]:
a+b

array([[ 6,  8],
       [10, 12]])

In [68]:
a*b

array([[ 5, 12],
       [21, 32]])

In [69]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [70]:
a.dot(b)

array([[19, 22],
       [43, 50]])